name: CI

on: workflow_dispatch

jobs:
  rollout-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-dev"

      - name: Run Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.SERVER }}
          REMOTE_USER: ${{ secrets.SERVER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "./"
          TARGET: "/srv/web/neuralseo.itron.pro/wp-content/plugins/neuralseo"
          ARGS: "-rav -e --delete"
          SCRIPT_BEFORE: mkdir -p /srv/web/neuralseo.itron.pro/wp-content/plugins/neuralseo
          SCRIPT_AFTER: chown -R www-data:www-data /srv/web/neuralseo.itron.pro/